apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jaeger-storage
  namespace: otel-poc
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi
