apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dashboard-provider-configmap.yaml
  - dashboards-configmap.yaml
  - collector-dashboard-configmap.yaml
  - deployment.yaml
