apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: otel-poc
resources:
  - namespace.yaml
  - rbac/
  - network-policies/
  - collector/
  - grafana/
  - jaeger/
  - loki/
  - prometheus/
  - alertmanager/
  - postgres/
  - services/
